# Generated by Django 2.2.4 on 2019-08-30 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import embed_video.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, verbose_name='имя')),
                ('surname', models.CharField(max_length=350, verbose_name='фамилия')),
                ('image', sorl.thumbnail.fields.ImageField(default='images/default.jpg', upload_to='images/', verbose_name='изображение')),
                ('web_site', models.CharField(blank=True, max_length=500, verbose_name='ссылка на сайт')),
                ('web_site_name', models.CharField(blank=True, max_length=150, verbose_name='название сайта')),
                ('e_mail', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('date_of_birth', models.IntegerField(blank=True, null=True, verbose_name='дата рождения')),
                ('date_of_dearth', models.IntegerField(blank=True, null=True, verbose_name='дата смерти')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='страна')),
                ('sport', models.CharField(max_length=500, verbose_name='вид активности')),
                ('diagnosis', models.CharField(max_length=500, verbose_name='диагноз')),
                ('surgery', models.CharField(blank=True, max_length=500, verbose_name='выполненная операция')),
                ('date_of_surgery', models.CharField(blank=True, max_length=250, null=True, verbose_name='дата проведения операции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('text', models.TextField(blank=True, null=True, verbose_name='текст')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, verbose_name='ссылка на видео')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='публиковать')),
            ],
            options={
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('description', models.TextField(max_length=1000, verbose_name='описание')),
                ('text', models.TextField(verbose_name='текст')),
                ('image', models.ImageField(blank=True, default='images/default.jpg', upload_to='images/', verbose_name='изображение')),
                ('image_name', models.CharField(blank=True, default='', max_length=100, verbose_name='подпись к изображению')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='ссылка на видео')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False, verbose_name='публиковать')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=False, verbose_name='открытый доступ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['published_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('description', models.TextField(max_length=1000, verbose_name='описание')),
                ('text', models.TextField(verbose_name='текст')),
                ('image', models.ImageField(blank=True, default='images/default.jpg', upload_to='images/', verbose_name='изображение')),
                ('image_name', models.CharField(blank=True, default='', max_length=100, verbose_name='подпись к изображению')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='ссылка на видео')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False, verbose_name='публиковать')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='ссылка на первоисточник')),
                ('link_name', models.CharField(blank=True, max_length=150, verbose_name='название ссылки')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['published_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('title', 'created_by'), name='уникальная запись'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('title', 'created_by'), name='уникальная запись'),
        ),
    ]
