# Generated by Django 2.2.4 on 2019-09-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0004_auto_20190901_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='code',
            field=models.TextField(default='yes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='code',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
