# Generated by Django 2.2.4 on 2019-09-01 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0005_auto_20190901_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='code',
        ),
        migrations.RemoveField(
            model_name='article',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='article',
            name='language',
        ),
        migrations.RemoveField(
            model_name='article',
            name='linenos',
        ),
        migrations.RemoveField(
            model_name='article',
            name='style',
        ),
        migrations.RemoveField(
            model_name='post',
            name='code',
        ),
        migrations.RemoveField(
            model_name='post',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='post',
            name='language',
        ),
        migrations.RemoveField(
            model_name='post',
            name='linenos',
        ),
        migrations.RemoveField(
            model_name='post',
            name='style',
        ),
    ]
